import type { TileTint } from '../components/SushiTile';

export interface CategoryTheme extends TileTint {
  emoji: string;
  accent: string;
}

export const CATEGORY_THEMES: Record<string, CategoryTheme> = {
  nigiri: {
    emoji: '🍣',
    accent: '#e53935',
    bg: '#fff5f4',
    bgActive: '#ffe3e0',
    border: '#fbd4d0',
    borderActive: '#f2938b',
    badge: '#e53935',
  },
  sashimi: {
    emoji: '🐟',
    accent: '#1e88e5',
    bg: '#eef6ff',
    bgActive: '#d9eaff',
    border: '#c9dff7',
    borderActive: '#7eb3ea',
    badge: '#1e88e5',
  },
  roll: {
    emoji: '🌀',
    accent: '#43a047',
    bg: '#f0faf1',
    bgActive: '#dbf0df',
    border: '#c9e6cd',
    borderActive: '#86c98f',
    badge: '#43a047',
  },
  handroll: {
    emoji: '🌯',
    accent: '#795548',
    bg: '#fdf5f0',
    bgActive: '#f5e6dc',
    border: '#e8d0c4',
    borderActive: '#c4947f',
    badge: '#795548',
  },
  special_roll: {
    emoji: '⭐',
    accent: '#f9a825',
    bg: '#fffde7',
    bgActive: '#fff8c5',
    border: '#fce88d',
    borderActive: '#f5c842',
    badge: '#f9a825',
  },
  salad: {
    emoji: '🥗',
    accent: '#558b2f',
    bg: '#f4fbe7',
    bgActive: '#e4f5cc',
    border: '#cce8a0',
    borderActive: '#8cc63f',
    badge: '#558b2f',
  },
  soup: {
    emoji: '🍜',
    accent: '#f57c00',
    bg: '#fff8e1',
    bgActive: '#ffecb3',
    border: '#ffe082',
    borderActive: '#ffc107',
    badge: '#f57c00',
  },
  special: {
    emoji: '⭐',
    accent: '#8e24aa',
    bg: '#faf3fc',
    bgActive: '#f0dffb',
    border: '#e4cbf0',
    borderActive: '#c084d8',
    badge: '#8e24aa',
  },
  dessert: {
    emoji: '🍡',
    accent: '#d81b60',
    bg: '#fdf0f6',
    bgActive: '#f8d7ea',
    border: '#f0b8d4',
    borderActive: '#e06fa5',
    badge: '#d81b60',
  },
  rice: {
    emoji: '🍚',
    accent: '#6d8c3d',
    bg: '#f8fbf0',
    bgActive: '#e8f2d3',
    border: '#d5e5b7',
    borderActive: '#a9c76f',
    badge: '#6d8c3d',
  },
  noodles: {
    emoji: '🍜',
    accent: '#c46a21',
    bg: '#fff6ec',
    bgActive: '#ffe4c9',
    border: '#f5cfa6',
    borderActive: '#de9b57',
    badge: '#c46a21',
  },
  teriyaki: {
    emoji: '🍱',
    accent: '#9c5a2e',
    bg: '#fff4ef',
    bgActive: '#f4dfd4',
    border: '#e5c5b5',
    borderActive: '#c58d70',
    badge: '#9c5a2e',
  },
  skewers: {
    emoji: '🍢',
    accent: '#546e7a',
    bg: '#f2f7f8',
    bgActive: '#dcebee',
    border: '#c5dbe0',
    borderActive: '#83a9b3',
    badge: '#546e7a',
  },
  spring_roll: {
    emoji: '🥬',
    accent: '#00897b',
    bg: '#eefaf8',
    bgActive: '#d5f1ec',
    border: '#b7e3dc',
    borderActive: '#62bdb0',
    badge: '#00897b',
  },
  other: {
    emoji: '🍚',
    accent: '#fb8c00',
    bg: '#fff7ea',
    bgActive: '#ffe9c7',
    border: '#ffd99e',
    borderActive: '#f5b661',
    badge: '#fb8c00',
  },
};

export function getCategoryTheme(category: string): CategoryTheme {
  return CATEGORY_THEMES[category] ?? CATEGORY_THEMES.other!;
}
