/* eslint-disable @typescript-eslint/no-require-imports -- static require() is required for Metro asset bundling */
import type { ImageSourcePropType } from 'react-native';

// Auto-generated map of menu imageKey -> 2-frame idle sprite SHEET (192x96, two 96px
// frames side by side; frame0 = rest, frame1 = raised 1px). See assets/pixel-assets/idle.
const IDLE_BY_KEY: Record<string, ImageSourcePropType> = {
  'dessert_any': require('../../assets/pixel-assets/idle/dessert_any.png'),
  'dessert_banana_tempura': require('../../assets/pixel-assets/idle/dessert_banana_tempura.png'),
  'dessert_cheesecake': require('../../assets/pixel-assets/idle/dessert_cheesecake.png'),
  'dessert_green_tea_ice_cream': require('../../assets/pixel-assets/idle/dessert_green_tea_ice_cream.png'),
  'dessert_ice_cream': require('../../assets/pixel-assets/idle/dessert_ice_cream.png'),
  'dessert_lava_cake': require('../../assets/pixel-assets/idle/dessert_lava_cake.png'),
  'dessert_mango_pudding': require('../../assets/pixel-assets/idle/dessert_mango_pudding.png'),
  'dessert_mochi': require('../../assets/pixel-assets/idle/dessert_mochi.png'),
  'dessert_tempura_ice_cream': require('../../assets/pixel-assets/idle/dessert_tempura_ice_cream.png'),
  'dessert_tiramisu': require('../../assets/pixel-assets/idle/dessert_tiramisu.png'),
  'handroll_any': require('../../assets/pixel-assets/idle/handroll_any.png'),
  'handroll_california': require('../../assets/pixel-assets/idle/handroll_california.png'),
  'handroll_salmon': require('../../assets/pixel-assets/idle/handroll_salmon.png'),
  'handroll_shrimp_tempura': require('../../assets/pixel-assets/idle/handroll_shrimp_tempura.png'),
  'handroll_spicy_tuna': require('../../assets/pixel-assets/idle/handroll_spicy_tuna.png'),
  'handroll_tuna': require('../../assets/pixel-assets/idle/handroll_tuna.png'),
  'handroll_yellowtail': require('../../assets/pixel-assets/idle/handroll_yellowtail.png'),
  'nigiri_any': require('../../assets/pixel-assets/idle/nigiri_any.png'),
  'nigiri_eel': require('../../assets/pixel-assets/idle/nigiri_eel.png'),
  'nigiri_egg': require('../../assets/pixel-assets/idle/nigiri_egg.png'),
  'nigiri_octopus': require('../../assets/pixel-assets/idle/nigiri_octopus.png'),
  'nigiri_salmon': require('../../assets/pixel-assets/idle/nigiri_salmon.png'),
  'nigiri_scallop': require('../../assets/pixel-assets/idle/nigiri_scallop.png'),
  'nigiri_shrimp': require('../../assets/pixel-assets/idle/nigiri_shrimp.png'),
  'nigiri_tuna': require('../../assets/pixel-assets/idle/nigiri_tuna.png'),
  'nigiri_yellowtail': require('../../assets/pixel-assets/idle/nigiri_yellowtail.png'),
  'noodles_any': require('../../assets/pixel-assets/idle/noodles_any.png'),
  'noodles_pad_thai': require('../../assets/pixel-assets/idle/noodles_pad_thai.png'),
  'noodles_ramen': require('../../assets/pixel-assets/idle/noodles_ramen.png'),
  'noodles_soba': require('../../assets/pixel-assets/idle/noodles_soba.png'),
  'noodles_udon': require('../../assets/pixel-assets/idle/noodles_udon.png'),
  'noodles_yaki_udon': require('../../assets/pixel-assets/idle/noodles_yaki_udon.png'),
  'rice_any': require('../../assets/pixel-assets/idle/rice_any.png'),
  'rice_chirashi': require('../../assets/pixel-assets/idle/rice_chirashi.png'),
  'rice_donburi': require('../../assets/pixel-assets/idle/rice_donburi.png'),
  'rice_fried': require('../../assets/pixel-assets/idle/rice_fried.png'),
  'rice_onigiri': require('../../assets/pixel-assets/idle/rice_onigiri.png'),
  'roll_any': require('../../assets/pixel-assets/idle/roll_any.png'),
  'roll_avocado': require('../../assets/pixel-assets/idle/roll_avocado.png'),
  'roll_california': require('../../assets/pixel-assets/idle/roll_california.png'),
  'roll_cucumber': require('../../assets/pixel-assets/idle/roll_cucumber.png'),
  'roll_philadelphia': require('../../assets/pixel-assets/idle/roll_philadelphia.png'),
  'roll_salmon': require('../../assets/pixel-assets/idle/roll_salmon.png'),
  'roll_salmon_avocado': require('../../assets/pixel-assets/idle/roll_salmon_avocado.png'),
  'roll_spicy_tuna': require('../../assets/pixel-assets/idle/roll_spicy_tuna.png'),
  'roll_tuna': require('../../assets/pixel-assets/idle/roll_tuna.png'),
  'roll_yellowtail': require('../../assets/pixel-assets/idle/roll_yellowtail.png'),
  'salad_any': require('../../assets/pixel-assets/idle/salad_any.png'),
  'salad_house': require('../../assets/pixel-assets/idle/salad_house.png'),
  'salad_mango': require('../../assets/pixel-assets/idle/salad_mango.png'),
  'salad_seaweed': require('../../assets/pixel-assets/idle/salad_seaweed.png'),
  'salad_sunomono': require('../../assets/pixel-assets/idle/salad_sunomono.png'),
  'sashimi_any': require('../../assets/pixel-assets/idle/sashimi_any.png'),
  'sashimi_octopus': require('../../assets/pixel-assets/idle/sashimi_octopus.png'),
  'sashimi_salmon': require('../../assets/pixel-assets/idle/sashimi_salmon.png'),
  'sashimi_scallop': require('../../assets/pixel-assets/idle/sashimi_scallop.png'),
  'sashimi_tuna': require('../../assets/pixel-assets/idle/sashimi_tuna.png'),
  'sashimi_yellowtail': require('../../assets/pixel-assets/idle/sashimi_yellowtail.png'),
  'skewers_any': require('../../assets/pixel-assets/idle/skewers_any.png'),
  'skewers_beef': require('../../assets/pixel-assets/idle/skewers_beef.png'),
  'skewers_chicken': require('../../assets/pixel-assets/idle/skewers_chicken.png'),
  'skewers_shrimp': require('../../assets/pixel-assets/idle/skewers_shrimp.png'),
  'skewers_veggie': require('../../assets/pixel-assets/idle/skewers_veggie.png'),
  'soup_any': require('../../assets/pixel-assets/idle/soup_any.png'),
  'soup_egg_drop': require('../../assets/pixel-assets/idle/soup_egg_drop.png'),
  'soup_hot_sour': require('../../assets/pixel-assets/idle/soup_hot_sour.png'),
  'soup_miso': require('../../assets/pixel-assets/idle/soup_miso.png'),
  'soup_seaweed': require('../../assets/pixel-assets/idle/soup_seaweed.png'),
  'soup_sumashi': require('../../assets/pixel-assets/idle/soup_sumashi.png'),
  'soup_tom_yum': require('../../assets/pixel-assets/idle/soup_tom_yum.png'),
  'soup_wonton': require('../../assets/pixel-assets/idle/soup_wonton.png'),
  'special_any': require('../../assets/pixel-assets/idle/special_any.png'),
  'special_edamame': require('../../assets/pixel-assets/idle/special_edamame.png'),
  'special_gyoza': require('../../assets/pixel-assets/idle/special_gyoza.png'),
  'special_roll_any': require('../../assets/pixel-assets/idle/special_roll_any.png'),
  'special_roll_caterpillar': require('../../assets/pixel-assets/idle/special_roll_caterpillar.png'),
  'special_roll_dragon': require('../../assets/pixel-assets/idle/special_roll_dragon.png'),
  'special_roll_dynamite': require('../../assets/pixel-assets/idle/special_roll_dynamite.png'),
  'special_roll_rainbow': require('../../assets/pixel-assets/idle/special_roll_rainbow.png'),
  'special_roll_shrimp_tempura': require('../../assets/pixel-assets/idle/special_roll_shrimp_tempura.png'),
  'special_roll_spider': require('../../assets/pixel-assets/idle/special_roll_spider.png'),
  'special_roll_volcano': require('../../assets/pixel-assets/idle/special_roll_volcano.png'),
  'spring_roll_any': require('../../assets/pixel-assets/idle/spring_roll_any.png'),
  'spring_roll_fresh': require('../../assets/pixel-assets/idle/spring_roll_fresh.png'),
  'spring_roll_pork': require('../../assets/pixel-assets/idle/spring_roll_pork.png'),
  'spring_roll_shrimp': require('../../assets/pixel-assets/idle/spring_roll_shrimp.png'),
  'spring_roll_vegetable': require('../../assets/pixel-assets/idle/spring_roll_vegetable.png'),
  'tempura_any': require('../../assets/pixel-assets/idle/tempura_any.png'),
  'tempura_chicken': require('../../assets/pixel-assets/idle/tempura_chicken.png'),
  'tempura_shrimp': require('../../assets/pixel-assets/idle/tempura_shrimp.png'),
  'tempura_vegetable': require('../../assets/pixel-assets/idle/tempura_vegetable.png'),
  'teriyaki_any': require('../../assets/pixel-assets/idle/teriyaki_any.png'),
  'teriyaki_beef': require('../../assets/pixel-assets/idle/teriyaki_beef.png'),
  'teriyaki_chicken': require('../../assets/pixel-assets/idle/teriyaki_chicken.png'),
  'teriyaki_salmon': require('../../assets/pixel-assets/idle/teriyaki_salmon.png'),
  'teriyaki_tofu': require('../../assets/pixel-assets/idle/teriyaki_tofu.png'),
};

const FALLBACK_KEY = 'nigiri_any';

/** Resolve the idle sprite sheet for a menu item, with the same fallback chain as getItemSprite. */
export function getItemIdleSheet(
  imageKey: string | undefined,
  category: string | undefined,
): ImageSourcePropType {
  if (imageKey && IDLE_BY_KEY[imageKey]) return IDLE_BY_KEY[imageKey]!;
  if (category) {
    const anyKey = `${category}_any`;
    if (IDLE_BY_KEY[anyKey]) return IDLE_BY_KEY[anyKey]!;
  }
  return IDLE_BY_KEY[FALLBACK_KEY]!;
}
